version: '3.8'

services:
  prometheus:
    container_name: blackbox-prometheus
    image: blackbox-prometheus:latest
    build: 
      context: .
      dockerfile: ./Dockerfile.prometheus
    volumes:
      - prome-data-blackbox:/opt/bitnami/prometheus/data
    ports:
      - 9090:9090
    networks:
      - localtest

  blackbox:
    container_name: water-blackbox
    image: water-blackbox:latest
    build: 
      context: .
      dockerfile: ./Dockerfile.blackbox
    ports:
      - 9115:9115
    networks:
      - localtest

  grafana:
    container_name: blackbox-grafana
    image: grafana/grafana:latest
    volumes:
      - grafana-data-blackbox:/var/lib/grafana 
    ports:
      - 3000:3000
    networks:
      - localtest

volumes:
  prome-data-blackbox:
  grafana-data-blackbox:

networks:
  localtest:
    name: localtest
    driver: bridge
